config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  resources :profiles, only: [:edit, :update, :show] do
    resources :carousels
    resources :hugs
    resources :coffes
    resources :accounts, only: [:update, :create, :index, :destroy]
    # member do
    #       get  'accounts/:id', to: 'accounts#index'
    #     end
  end

  get '/profiles/:profile_id/accounts/:id', to: 'accounts#index', as: :edit_profile_account



  root 'homes#index'


end

# resources :users do
#   resources :certifications, only: [:new, :edit,:create]
#   resources :hobbies
#   member do
#     get 'user_fish', to: 'users#user_fish', as: :fish
#   end
# end
# root 'welcome#show'

app/models/carousel.rb
# == Schema Information
#
# Table name: carousels
#
#  id         :integer          not null, primary key
#  subtitle   :text
#  profile_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Carousel < ApplicationRecord
  belongs_to :profile
  has_one_attached :img
end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController


  before_action :set_carousel, only: [:show, :edit, :update, :destroy]
  before_action :set_profile

  layout 'barra'



def new
  @carousel =  Carousel.new
  @profile = Profile.find(params[:profile_id])
end

def create
  # @profile = Profile.find(params[:profile_id])
  @carousel = @profile.carousel.build(carousel_params)
  # @carousel = Carousel.new(carousel_params)
  @carousel.save

  if @carousel.save
      redirect_to  profile_carousels_path(@profile)
    else
      redirect_to profile_carousels_path(@profile)
    end

end

def index
  @carousels = Carousel.all
end


def destroy
  @carousel.destroy
  if @carousel.destroy
    redirect_to profile_carousels_path(@profile)
  else
    redirect_to edit_profile_path(current_user.profile.id)
  end
end

def update
  if @carousel.update(carousel_params)
    redirect_to profile_carousels_path(@profile)
  else
    redirect_to edit_profile_path(current_user.profile.id)
  end
end



private

def set_carousel
  @carousel = Carousel.find(params[:id])
end
def set_profile
  @profile = Profile.find(params[:profile_id])
end




def carousel_params
  params.require(:carousel).permit(:subtitle, :img)
end


end

app/helpers/carousels_helper.rb
module CarouselsHelper
end

app/views/carousels/_form.html.haml
.container-fluid
  = form_with(model: [@profile, @carousel], local: true ) do |f|
    - if current_user.profile.errors.any?
      #error_explanation
        %h2= "#{pluralize(current_user.profile.errors.count, "error")} prohibited this profile from being saved:"
        %ul
          - current_user.profile.full_messages.each do |message|
            %li= message
    .row
      .col-4.alargando
        .ala
          .card-title
            %h1.eltit-atneuc Imagen del carousel
          .card-text
            %pre.txet-atneuc
              :preserve
                Parametros de publicacion y leyenda de
                la imagen a mostrarse en el carousel
      .col-8.alargando
        .card-body.re
          = f.file_field :img, class: 'dropify rounded yfipord'
          %p.yess Imagen principal
          = link_to = f.label :img do
            %p.knil Cargar imagen
    .row
      .col
        .row
          .col-4.alargando
            .ven.ala
              .card-title
                %h1.eltit-atneuc Datos de la imagen
              .card-text
                %pre.txet-atneuc
                  :preserve
                    Agregar imagen que se mostrara en el
                    carousel del perfil publico
          .col-8.alargando
            .card-body.text-center.fondo.rounded
              .field
                .card-title
                  = f.label "Subtitulo", class: 'satrel mover'
                .card-text
                  = f.text_field :subtitle, class: 'rounded tamano'
        .row
          .jojo.border-top
            .actions
              = f.submit 'Guardar', class: ' btn ntb xs'

app/views/carousels/edit.html.haml
.row.row-color
  = link_to profile_carousels_path(current_user.profile.id) do
    #{image_tag('back.svg', class: 'lista-de-imagenes')}
  %h1.letras-title.border-bottom Agregar imagen
.row.row-color-form
  .col
    = render 'form'

app/views/carousels/index.html.haml
.row.row-color
  %h1.letras-title.border-bottom Carousel de imagenes
  = link_to new_profile_carousel_path(current_user.profile.id) do
    #{image_tag('Button_guardar.svg', class: 'button_guardar text-right')}
.row.row-color-form
  .col
    .row.siza
      .col.card.rounded
        .row.w.border-bottom.text-center
          %h5.senegami_text Imagenes
        .row.wa.border-bottom
        - @carousels.each do |carouselito|
          .row.w.border-bottom
            .col-1.text-center
              = image_tag carouselito.img, class: 'img_caro'
            .col-10
              %P.omitlu
              = carouselito.subtitle
            .col-1
              .trespuntoss.text-center
                = image_tag 'Vector.svg', class: 'vectora'
                .edit_delete.border
                  .edit_container
                    = link_to('Edit', "/profiles/#{@profile.id}/carousels/#{carouselito.id}/edit", class: "Edit")
                  .delete_container
                    = link_to('Delete', "/profiles/#{@profile.id}/carousels/#{carouselito.id}", method: :delete, data: { confirm: 'Are you sure?' }, class: "Delete")

app/views/carousels/new.html.haml
.row.row-color
  = link_to profile_carousels_path(current_user.profile.id) do
    #{image_tag('back.svg', class: 'lista-de-imagenes')}
  %h1.letras-title.border-bottom Agregar imagen
.row.row-color-form
  .col
    = render 'form'