config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  resources :profiles, only: [:edit, :update, :show] do
    resources :carousels
    resources :hugs
    resources :coffes
    resources :accounts, only: [:update, :create, :index, :destroy]
    # member do
    #       get  'accounts/:id', to: 'accounts#index'
    #     end
  end

  get '/profiles/:profile_id/accounts/:id', to: 'accounts#index', as: :edit_profile_account



  root 'homes#index'


end

# resources :users do
#   resources :certifications, only: [:new, :edit,:create]
#   resources :hobbies
#   member do
#     get 'user_fish', to: 'users#user_fish', as: :fish
#   end
# end
# root 'welcome#show'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %link{:href => "https://fonts.googleapis.com/css?family=Happy+Monkey", :rel => "stylesheet"}/

    %link{:href => "https://fonts.googleapis.com/css?family=Roboto", :rel => "stylesheet"}/


  %body
    %p.notice
      =notice
    %p.alert
      =alert

      = yield

app/views/layouts/barra.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %link{:href => "https://fonts.googleapis.com/css?family=Happy+Monkey", :rel => "stylesheet"}/

    %link{:href => "https://fonts.googleapis.com/css?family=Roboto", :rel => "stylesheet"}/


  %body
  .container-fluid
    .row.row1
      .col-2.ayc-background-color.text-center
        = link_to edit_profile_path(current_user.profile) do
          #{image_tag('A&C.svg', class: "AyC")}
      .col-8.background-searh-photo.text-center
        %input.mySearch.rounded.vcenter{:placeholder => "", :type => "search"}/
      .col-2
        .row
          .col-1.col-linea
            .linea.margin-righ
          .col-2.pintando
            .card-img.div-photo
              = image_tag current_user.profile.img_locura, class: 'photo'
          .col.blue-loco
            .card-text.camarada
              - if current_user.profile.fullname.nil?
                = current_user.email
              - else
                = current_user.profile.fullname
    .row.profile-edit
      .col-2.menu.border-right
        %nav.nav.flex-column.big-nav
          %nav.nav.nav-nav
            = link_to edit_profile_path(current_user.profile) do
              #{image_tag('perfil.svg', class: "menu-img-profile")}
            %a.nav-link{:href => edit_profile_path(current_user.profile)}
              %p.letras Perfil

          %nav.nav.nav-nav2
            = link_to  profile_carousels_path(current_user.profile) do
              #{image_tag('perfil.svg', class: "menu-img-profile")}
            %a.nav-link{:href => profile_carousels_path(current_user.profile)}
              %p.letras Imagenes

          %nav.nav.nav-nav2
            = link_to profile_accounts_path(current_user.profile) do
              #{image_tag('cuentas.svg', class: "menu-img-profile")}
            %a.nav-link{:href => profile_accounts_path(current_user.profile)}
              %p.letras1 Cuentas
      .col-10
        =yield